# Generated by Django 5.2.17 on 2026-08-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_image',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen Personalizada (URL o Base64)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Personalizado'),
        ),
    ]
