# Generated by Django 5.2.17 on 2026-08-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_custom_image_orderitem_custom_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='device_models/', verbose_name='Imagen del Modelo'),
        ),
    ]
